LISTINGS = [{'id': 'resource-3d-01',
  'name': 'Maker Corner',
  'type': 'resource',
  'category': '3D printer',
  'title': 'Borrow a 3D printer by the hour',
  'description': 'Community maker space with a calibrated 3D printer. Bring your STL file; filament costs '
                 'are charged separately.',
  'distanceKm': 1.3,
  'trustScore': 91,
  'rating': 4.8,
  'reviewCount': 16,
  'verified': True,
  'live': False,
  'price': '₹150 / hour',
  'image': 'https://images.unsplash.com/photo-1631553127987-5e8e6e3a2b5b?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9912,
  'lng': 77.7039,
  'reviews': [{'name': 'Dev P.',
               'rating': 5,
               'text': 'Helpful with first-time prints.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 88, 'repeatCustomers': 80}},
 {'id': 'resource-drill-02',
  'name': "Ramesh's Tool Shelf",
  'type': 'resource',
  'category': 'Power tools',
  'title': 'Drill and home-repair tools',
  'description': 'Lendable drill, screwdriver set and basic home-repair tools. Pickup and return times '
                 'arranged in chat.',
  'distanceKm': 0.6,
  'trustScore': 82,
  'rating': 4.6,
  'reviewCount': 12,
  'verified': True,
  'live': False,
  'price': 'From ₹80 / day',
  'image': 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9863,
  'lng': 77.7008,
  'reviews': [{'name': 'Kunal B.',
               'rating': 5,
               'text': 'Tools were in good condition.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 72, 'repeatCustomers': 61}},
 {'id': 'resource-guitar-03',
  'name': "Mira's Music Room",
  'type': 'resource',
  'category': 'Musical instrument',
  'title': 'Acoustic guitar for practice',
  'description': 'Borrow a well-maintained acoustic guitar for practice or a small gathering. ID check at '
                 'pickup.',
  'distanceKm': 1.7,
  'trustScore': 88,
  'rating': 4.9,
  'reviewCount': 9,
  'verified': True,
  'live': False,
  'price': '₹120 / day',
  'image': 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9784,
  'lng': 77.7077,
  'reviews': [{'name': 'Tanya G.',
               'rating': 5,
               'text': 'Lovely instrument and easy pickup.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 84, 'repeatCustomers': 75}},
 {'id': 'vendor-chai-01',
  'name': 'Sharma Chai Point',
  'type': 'vendor',
  'category': 'Chai & snacks',
  'title': 'Fresh chai near the market',
  'description': 'Masala chai, ginger tea and quick snacks. Usually set up beside the neighbourhood market '
                 'entrance.',
  'distanceKm': 0.3,
  'trustScore': 93,
  'rating': 4.9,
  'reviewCount': 51,
  'verified': True,
  'live': True,
  'price': 'From ₹10',
  'image': 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9837,
  'lng': 77.7092,
  'reviews': [{'name': 'Vikas T.',
               'rating': 5,
               'text': 'My daily morning chai stop.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 91, 'repeatCustomers': 90}},
 {'id': 'vendor-veg-02',
  'name': 'Fresh Basket Rehri',
  'type': 'vendor',
  'category': 'Vegetables',
  'title': 'Seasonal vegetables today',
  'description': "Fresh seasonal vegetables sourced early each morning. Message before coming for today's "
                 'availability.',
  'distanceKm': 0.9,
  'trustScore': 87,
  'rating': 4.7,
  'reviewCount': 32,
  'verified': True,
  'live': True,
  'price': 'Market price',
  'image': 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9895,
  'lng': 77.7154,
  'reviews': [{'name': 'Shalini D.',
               'rating': 5,
               'text': 'Fresh produce and fair prices.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 78, 'repeatCustomers': 76}},
 {'id': 'vendor-repair-03',
  'name': 'Imran Mobile Repair',
  'type': 'vendor',
  'category': 'Mobile repair',
  'title': 'Phone repairs near bus stand',
  'description': 'Screen guards, charging-port checks and common phone repairs. Ask for an estimate before '
                 'work begins.',
  'distanceKm': 1.4,
  'trustScore': 79,
  'rating': 4.5,
  'reviewCount': 17,
  'verified': True,
  'live': True,
  'price': 'Inspection from ₹50',
  'image': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9769,
  'lng': 77.7182,
  'reviews': [{'name': 'Deepak N.',
               'rating': 4,
               'text': 'Quick service for a charging issue.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 67, 'repeatCustomers': 58}},
 {'id': 'vendor-fruit-04',
  'name': 'Nisha Fruit Cart',
  'type': 'vendor',
  'category': 'Fruit vendor',
  'title': 'Fruit cart by the park',
  'description': 'Bananas, guavas, oranges and seasonal fruit. The cart moves around the park entrance in '
                 'the evening.',
  'distanceKm': 1.0,
  'trustScore': 84,
  'rating': 4.6,
  'reviewCount': 21,
  'verified': True,
  'live': True,
  'price': 'From ₹20',
  'image': 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9811,
  'lng': 77.6975,
  'reviews': [{'name': 'Meenal A.', 'rating': 5, 'text': 'Good seasonal fruit.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 74, 'repeatCustomers': 68}},
 {'id': 'resource-ladder-04',
  'name': 'Neighbourhood Fix-It Kit',
  'type': 'resource',
  'category': 'DIY tools',
  'title': 'Ladder and repair kit to borrow',
  'description': 'A sturdy ladder, measuring tape and basic tool kit for small household jobs. Please return '
                 'items clean and on time.',
  'distanceKm': 2.3,
  'trustScore': 76,
  'rating': 4.4,
  'reviewCount': 8,
  'verified': False,
  'live': False,
  'price': '₹60 / day',
  'image': 'https://images.unsplash.com/photo-1581147036324-c1c89c2c8a2f?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9722,
  'lng': 77.7114,
  'reviews': [{'name': 'Harish L.',
               'rating': 4,
               'text': 'Useful for a quick home project.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 60, 'completedBookings': 70, 'repeatCustomers': 55}}]
