LISTINGS = [{'id': 'resource-3d-01',
  'name': 'Maker Corner',
  'type': 'resource',
  'category': '3D printer',
  'title': 'Borrow a 3D printer by the hour',
  'description': 'Community maker space with a calibrated 3D printer. Bring your STL file; filament costs '
                 'are charged separately.',
  'distanceKm': 1.3,
  'trustScore': 91,
  'rating': 4.8,
  'reviewCount': 16,
  'verified': True,
  'live': False,
  'price': '₹150 / hour',
  'image': 'https://images.unsplash.com/photo-1631553127987-5e8e6e3a2b5b?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9912,
  'lng': 77.7039,
  'reviews': [{'name': 'Dev P.',
               'rating': 5,
               'text': 'Helpful with first-time prints.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 88, 'repeatCustomers': 80}},
 {'id': 'resource-drill-02',
  'name': "Ramesh's Tool Shelf",
  'type': 'resource',
  'category': 'Power tools',
  'title': 'Drill and home-repair tools',
  'description': 'Lendable drill, screwdriver set and basic home-repair tools. Pickup and return times '
                 'arranged in chat.',
  'distanceKm': 0.6,
  'trustScore': 82,
  'rating': 4.6,
  'reviewCount': 12,
  'verified': True,
  'live': False,
  'price': 'From ₹80 / day',
  'image': 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9863,
  'lng': 77.7008,
  'reviews': [{'name': 'Kunal B.',
               'rating': 5,
               'text': 'Tools were in good condition.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 72, 'repeatCustomers': 61}},
 {'id': 'resource-guitar-03',
  'name': "Mira's Music Room",
  'type': 'resource',
  'category': 'Musical instrument',
  'title': 'Acoustic guitar for practice',
  'description': 'Borrow a well-maintained acoustic guitar for practice or a small gathering. ID check at '
                 'pickup.',
  'distanceKm': 1.7,
  'trustScore': 88,
  'rating': 4.9,
  'reviewCount': 9,
  'verified': True,
  'live': False,
  'price': '₹120 / day',
  'image': 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9784,
  'lng': 77.7077,
  'reviews': [{'name': 'Tanya G.',
               'rating': 5,
               'text': 'Lovely instrument and easy pickup.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 84, 'repeatCustomers': 75}},
 {'id': 'vendor-chai-01',
  'name': 'Sharma Chai Point',
  'type': 'vendor',
  'category': 'Chai & snacks',
  'title': 'Fresh chai near the market',
  'description': 'Masala chai, ginger tea and quick snacks. Usually set up beside the neighbourhood market '
                 'entrance.',
  'distanceKm': 0.3,
  'trustScore': 93,
  'rating': 4.9,
  'reviewCount': 51,
  'verified': True,
  'live': True,
  'price': 'From ₹10',
  'image': 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9837,
  'lng': 77.7092,
  'reviews': [{'name': 'Vikas T.',
               'rating': 5,
               'text': 'My daily morning chai stop.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 91, 'repeatCustomers': 90}},
 {'id': 'vendor-veg-02',
  'name': 'Fresh Basket Rehri',
  'type': 'vendor',
  'category': 'Vegetables',
  'title': 'Seasonal vegetables today',
  'description': "Fresh seasonal vegetables sourced early each morning. Message before coming for today's "
                 'availability.',
  'distanceKm': 0.9,
  'trustScore': 87,
  'rating': 4.7,
  'reviewCount': 32,
  'verified': True,
  'live': True,
  'price': 'Market price',
  'image': 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9895,
  'lng': 77.7154,
  'reviews': [{'name': 'Shalini D.',
               'rating': 5,
               'text': 'Fresh produce and fair prices.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 78, 'repeatCustomers': 76}},
 {'id': 'vendor-repair-03',
  'name': 'Imran Mobile Repair',
  'type': 'vendor',
  'category': 'Mobile repair',
  'title': 'Phone repairs near bus stand',
  'description': 'Screen guards, charging-port checks and common phone repairs. Ask for an estimate before '
                 'work begins.',
  'distanceKm': 1.4,
  'trustScore': 79,
  'rating': 4.5,
  'reviewCount': 17,
  'verified': True,
  'live': True,
  'price': 'Inspection from ₹50',
  'image': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9769,
  'lng': 77.7182,
  'reviews': [{'name': 'Deepak N.',
               'rating': 4,
               'text': 'Quick service for a charging issue.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 67, 'repeatCustomers': 58}},
 {'id': 'vendor-fruit-04',
  'name': 'Nisha Fruit Cart',
  'type': 'vendor',
  'category': 'Fruit vendor',
  'title': 'Fruit cart by the park',
  'description': 'Bananas, guavas, oranges and seasonal fruit. The cart moves around the park entrance in '
                 'the evening.',
  'distanceKm': 1.0,
  'trustScore': 84,
  'rating': 4.6,
  'reviewCount': 21,
  'verified': True,
  'live': True,
  'price': 'From ₹20',
  'image': 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9811,
  'lng': 77.6975,
  'reviews': [{'name': 'Meenal A.', 'rating': 5, 'text': 'Good seasonal fruit.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 74, 'repeatCustomers': 68}},
 {'id': 'resource-ladder-04',
  'name': 'Neighbourhood Fix-It Kit',
  'type': 'resource',
  'category': 'DIY tools',
  'title': 'Ladder and repair kit to borrow',
  'description': 'A sturdy ladder, measuring tape and basic tool kit for small household jobs. Please return '
                 'items clean and on time.',
  'distanceKm': 2.3,
  'trustScore': 76,
  'rating': 4.4,
  'reviewCount': 8,
  'verified': False,
  'live': False,
  'price': '₹60 / day',
  'image': 'https://images.unsplash.com/photo-1581147036324-c1c89c2c8a2f?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9722,
  'lng': 77.7114,
  'reviews': [{'name': 'Harish L.',
               'rating': 4,
               'text': 'Useful for a quick home project.',
               'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 60, 'completedBookings': 70, 'repeatCustomers': 55}},
 {'id': 'resource-infrastructure-05',
  'name': 'Meerut Community Workroom',
  'type': 'resource',
  'category': 'Infrastructure',
  'title': 'Shared meeting and work space',
  'description': 'A bookable community room with tables, power outlets and accessible seating for study groups and small meetings.',
  'distanceKm': 1.1,
  'trustScore': 90,
  'rating': 4.8,
  'reviewCount': 14,
  'verified': True,
  'live': False,
  'price': '₹200 / hour',
  'image': 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9874,
  'lng': 77.7121,
  'reviews': [{'name': 'Anita R.', 'rating': 5, 'text': 'Clean, convenient and easy to book.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 86, 'repeatCustomers': 78}},
 {'id': 'resource-consumables-06',
  'name': 'Green Basket Supplies',
  'type': 'resource',
  'category': 'Consumables',
  'title': 'Garden soil and seasonal seeds',
  'description': 'Locally stocked potting mix, compost and seasonal seeds for balcony and home gardens.',
  'distanceKm': 1.5,
  'trustScore': 85,
  'rating': 4.7,
  'reviewCount': 11,
  'verified': True,
  'live': False,
  'price': 'From ₹40',
  'image': 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9798,
  'lng': 77.7133,
  'reviews': [{'name': 'Ritu S.', 'rating': 5, 'text': 'Healthy seedlings and helpful advice.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 75, 'repeatCustomers': 70}},
 {'id': 'resource-skills-07',
  'name': 'Asha Learning & Care',
  'type': 'resource',
  'category': 'Human & skills',
  'title': 'Neighbourhood tutoring and homework help',
  'description': 'Patient one-to-one support in maths and science for school students, with flexible evening sessions.',
  'distanceKm': 0.8,
  'trustScore': 94,
  'rating': 5.0,
  'reviewCount': 19,
  'verified': True,
  'live': False,
  'price': '₹300 / hour',
  'image': 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9851,
  'lng': 77.7049,
  'reviews': [{'name': 'Pooja M.', 'rating': 5, 'text': 'Clear explanations and a supportive teacher.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 92, 'repeatCustomers': 88}},
 {'id': 'resource-commercials-08',
  'name': 'Local Business Hub',
  'type': 'resource',
  'category': 'Commercials',
  'title': 'Small shop counter for a day',
  'description': 'Short-term counter space near the market for local makers and small businesses. Includes basic power access.',
  'distanceKm': 1.9,
  'trustScore': 81,
  'rating': 4.5,
  'reviewCount': 7,
  'verified': True,
  'live': False,
  'price': '₹500 / day',
  'image': 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9767,
  'lng': 77.7105,
  'reviews': [{'name': 'Sahil K.', 'rating': 5, 'text': 'Good footfall for a weekend pop-up.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 68, 'repeatCustomers': 60}},
 {'id': 'resource-transport-09',
  'name': 'Neighbourhood Cargo Cycle',
  'type': 'resource',
  'category': 'Transport & logistics',
  'title': 'Cargo bicycle for local pickups',
  'description': 'Borrow a sturdy cargo cycle for local errands, moving boxes or collecting market supplies.',
  'distanceKm': 1.2,
  'trustScore': 83,
  'rating': 4.6,
  'reviewCount': 10,
  'verified': True,
  'live': False,
  'price': '₹100 / day',
  'image': 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9903,
  'lng': 77.7071,
  'reviews': [{'name': 'Amit G.', 'rating': 5, 'text': 'Very handy for nearby deliveries.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 74, 'repeatCustomers': 66}},
 {'id': 'resource-connectivity-10',
  'name': 'Study Spot Wi-Fi',
  'type': 'resource',
  'category': 'Digital & connectivity',
  'title': 'Quiet study desk with reliable Wi-Fi',
  'description': 'A quiet desk with power and fast Wi-Fi for remote work, online classes or video calls.',
  'distanceKm': 0.7,
  'trustScore': 88,
  'rating': 4.8,
  'reviewCount': 13,
  'verified': True,
  'live': False,
  'price': '₹80 / hour',
  'image': 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9829,
  'lng': 77.7027,
  'reviews': [{'name': 'Neha J.', 'rating': 5, 'text': 'Great internet and a peaceful setup.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 82, 'repeatCustomers': 76}},
 {'id': 'resource-wellbeing-11',
  'name': 'Parkside Yoga Circle',
  'type': 'resource',
  'category': 'Health & wellbeing',
  'title': 'Small-group morning yoga',
  'description': 'Friendly beginner sessions in the neighbourhood park. Bring a mat or ask to borrow one.',
  'distanceKm': 1.6,
  'trustScore': 86,
  'rating': 4.8,
  'reviewCount': 15,
  'verified': True,
  'live': False,
  'price': '₹150 / session',
  'image': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9748,
  'lng': 77.7059,
  'reviews': [{'name': 'Kavita B.', 'rating': 5, 'text': 'Welcoming class with options for beginners.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 78, 'repeatCustomers': 73}},
 {'id': 'resource-venue-12',
  'name': 'Shastri Nagar Community Hall',
  'type': 'resource',
  'category': 'Spaces & venues',
  'title': 'Community hall for small events',
  'description': 'Flexible indoor space for workshops, family gatherings and neighbourhood meetings, with chairs and tables included.',
  'distanceKm': 2.0,
  'trustScore': 80,
  'rating': 4.5,
  'reviewCount': 8,
  'verified': True,
  'live': False,
  'price': 'From ₹800 / event',
  'image': 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9709,
  'lng': 77.7161,
  'reviews': [{'name': 'Mohan L.', 'rating': 5, 'text': 'A practical space for a family gathering.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 72, 'repeatCustomers': 64}},
 {'id': 'resource-books-13',
  'name': 'Neighbourhood Book Shelf',
  'type': 'resource',
  'category': 'Books & study',
  'title': 'School books and exam guides',
  'description': 'Borrow school textbooks, competitive-exam guides and novels from a shared neighbourhood shelf.',
  'distanceKm': 1.4,
  'trustScore': 89,
  'rating': 4.8,
  'reviewCount': 17,
  'verified': True,
  'live': False,
  'price': 'Free to borrow',
  'image': 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9881,
  'lng': 77.6998,
  'reviews': [{'name': 'Suman P.', 'rating': 5, 'text': 'Found the exam guide I needed.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 84, 'repeatCustomers': 80}},
 {'id': 'resource-household-14',
  'name': 'Anjali Home Share',
  'type': 'resource',
  'category': 'Home & community',
  'title': 'Kitchen and household essentials',
  'description': 'Share a pressure cooker, folding table, storage boxes and other household items with nearby neighbours.',
  'distanceKm': 0.9,
  'trustScore': 84,
  'rating': 4.7,
  'reviewCount': 12,
  'verified': True,
  'live': False,
  'price': 'From ₹30 / day',
  'image': 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9807,
  'lng': 77.7068,
  'reviews': [{'name': 'Radhika N.', 'rating': 5, 'text': 'Very useful for a family get-together.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 76, 'repeatCustomers': 68}},
 {'id': 'resource-recreation-15',
  'name': 'Parkside Sports Share',
  'type': 'resource',
  'category': 'Recreation & events',
  'title': 'Sports and event gear to borrow',
  'description': 'Borrow badminton rackets, footballs, picnic mats and basic party gear for a neighbourhood activity.',
  'distanceKm': 1.8,
  'trustScore': 86,
  'rating': 4.8,
  'reviewCount': 14,
  'verified': True,
  'live': False,
  'price': 'From ₹50 / day',
  'image': 'https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9759,
  'lng': 77.7006,
  'reviews': [{'name': 'Rohan D.', 'rating': 5, 'text': 'The rackets were in great condition.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 79, 'repeatCustomers': 72}},
 {'id': 'resource-creative-16',
  'name': 'Mira Makes & Mends',
  'type': 'resource',
  'category': 'Creative & repair skills',
  'title': 'Sewing machine and basic tailoring help',
  'description': 'Use a home sewing machine or get help with small clothing repairs and beginner stitching projects.',
  'distanceKm': 1.0,
  'trustScore': 91,
  'rating': 4.9,
  'reviewCount': 16,
  'verified': True,
  'live': False,
  'price': 'From ₹70',
  'image': 'https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9868,
  'lng': 77.7192,
  'reviews': [{'name': 'Tanya G.', 'rating': 5, 'text': 'Quick repair and very kind guidance.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 87, 'repeatCustomers': 82}},
 {'id': 'resource-equipment-17',
  'name': 'Community Equipment Locker',
  'type': 'resource',
  'category': 'Tools & equipment',
  'title': 'Cleaning and project equipment',
  'description': 'Short-term access to a vacuum cleaner, extension ladder and power washer for home projects.',
  'distanceKm': 1.7,
  'trustScore': 82,
  'rating': 4.6,
  'reviewCount': 9,
  'verified': True,
  'live': False,
  'price': 'From ₹100 / day',
  'image': 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80',
  'lat': 28.9781,
  'lng': 77.7147,
  'reviews': [{'name': 'Harish L.', 'rating': 5, 'text': 'Everything was clean and ready to use.', 'verifiedBooking': True}],
  'trustBreakdown': {'idVerified': 100, 'completedBookings': 73, 'repeatCustomers': 65}}]
